### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lyufan** [LukasStruppek/Plug-and-Play-Attacks#1]
Hello, I executed this command in docker:`python attack.py -c=configs/attacking/default_attacking_local.yaml` and my GPU has plenty of memory, but I got this error:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/33341810/220826601-dc0a9da6-fc40-4dd5-8e10-fd149c541302.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/33341810/220826697-942dc58d-ba8d-4fdb-81ed-801dd6ef0c5a.png">
I have no clue how to resolve it. Please help

**Comment by LukasStruppek** [comment]
Hey, did you try to reduce the batch size in the config file? The StyleGAN2 and target models already need a significant amount of GPU memory and since the attack backpropagates through both of them, even more memory is used. The batch size in the config file is for a single GPU, so if you use, e.g., 4 GPUs, it is multiplied by factor 4. As the GPU memory requirements in the readme show, a batch size of 10 with a 1024x1024 StyleGAN model already requires more than 15GB of memory. So maybe start with a value of 5.

**Comment by lyufan** [comment]
Thanks for your reply！I've tried reducing the batch size to 5 or smaller, but still got the same results.And there's another question,I created the docker container with `--gpus all`,but everytime only one GPU is used(no other code changed).

**Comment by lyufan** [comment]
I’m so sorry for my mistake.I only changed the batch-size in 'candidates',and didn't change the batch-size in 'attack', I'm sorry to bother you.

**Comment by LukasStruppek** [comment]
No problem, I am glad that the problem is solved :)
