### ISSUE TITLE
Computational time of performing attack on CelebA

### ISSUE THREAD

**Issue by SCccc21** [LukasStruppek/Plug-and-Play-Attacks#3]
Hi,

I'm currently running the code following the instruction on CelebA_FFHQ attack setting. The experiment takes an extremely long time: I am using 4 NVIDIA RTX A6000 gpus doing data-parallel optimization, and the job has already been running for one day. 

May I ask the exact time you used for running attack on this setting? Thanks.

**Comment by LukasStruppek** [comment]
Hey,
I recently ran an experiment using the ffhq StyleGAN to attack a ResNet-101 with 500 classes. It took roughly 14h on a single NVIDIA A100-SXM4-80GB. However, I set 
`num_candidates: 50`
`samples_per_target: 25`
in the config, with 200 candidates it would take about four times as long. So to speed up the attack, you could change those two parameters.

Also, using a StyleGAN with a lower output resolution, e.g., 264x264 also significantly improves the speed. But it comes at the cost of training a fresh StyleGAN on this resolution since Nvidia only offers a 1024x1024 FFHQ model.

**Comment by SCccc21** [comment]
Thanks Lukas, that's really helpful! But is the performance sensitive to these two params? As currently I am using 200 candidates and 50 samples per target, not sure if the performance will have large drop if I limit the number of candidates.

**Comment by LukasStruppek** [comment]
It probably degrades by a few percentage points but is the simplest option to speed things up. I would not expect large drops in the results.

**Comment by SCccc21** [comment]
I see, thanks! I'll have a try.

**Comment by SCccc21** [comment]
May I ask why you set batch_size=batch_size*2 in `class_acc_evaluator.compute_acc(
            w_optimized_unselected, targets, synthesis, config, batch_size=batch_size * 2, resize=299, rtpt=rtpt)`; while set batch_size = batch_size * 10 in `perform_final_selection`？

**Comment by SCccc21** [comment]
May I ask what is the scale of target_loss during training? It seems my target loss is 9.9057 after optimization. Is it normal or too high?

**Comment by LukasStruppek** [comment]
Yes, that is quite normal that the loss stays high. You should, however, see the mean_conf value increase and approach 1.0. Some common mistake is to use the wrong normalization of the generated images, so their distribution does not align with the target model, e.g., the target model is trained within pixel range [0,1] and the generated input images are in range[-1,1]. But then the mean confidence should stay rather low.
